"""add_profiles_and_owner_ids_v4

Revision ID: 3bde872f9e1f
Revises: add_mineru_fields
Create Date: 2026-01-18 23:34:10.134130

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '3bde872f9e1f'
down_revision: Union[str, Sequence[str], None] = 'add_mineru_fields'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profiles',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('credits', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('comparison_documents', sa.Column('owner_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_index(op.f('ix_comparison_documents_owner_id'), 'comparison_documents', ['owner_id'], unique=False)
    op.add_column('comparison_results', sa.Column('owner_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_index(op.f('ix_comparison_results_owner_id'), 'comparison_results', ['owner_id'], unique=False)
    op.add_column('documents', sa.Column('owner_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_index(op.f('ix_documents_owner_id'), 'documents', ['owner_id'], unique=False)
    op.add_column('review_result_items', sa.Column('owner_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_index(op.f('ix_review_result_items_owner_id'), 'review_result_items', ['owner_id'], unique=False)
    op.add_column('review_tasks', sa.Column('owner_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('review_tasks', sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_index(op.f('ix_review_tasks_owner_id'), 'review_tasks', ['owner_id'], unique=False)
    op.add_column('rule_groups', sa.Column('owner_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_index(op.f('ix_rule_groups_owner_id'), 'rule_groups', ['owner_id'], unique=False)
    op.add_column('rules', sa.Column('owner_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_index(op.f('ix_rules_owner_id'), 'rules', ['owner_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('profiles')
    op.drop_index(op.f('ix_rules_owner_id'), table_name='rules')
    op.drop_column('rules', 'owner_id')
    op.drop_index(op.f('ix_rule_groups_owner_id'), table_name='rule_groups')
    op.drop_column('rule_groups', 'owner_id')
    op.drop_index(op.f('ix_review_tasks_owner_id'), table_name='review_tasks')
    op.drop_column('review_tasks', 'error_message')
    op.drop_column('review_tasks', 'owner_id')
    op.drop_index(op.f('ix_review_result_items_owner_id'), table_name='review_result_items')
    op.drop_column('review_result_items', 'owner_id')
    op.drop_index(op.f('ix_documents_owner_id'), table_name='documents')
    op.drop_column('documents', 'owner_id')
    op.drop_index(op.f('ix_comparison_results_owner_id'), table_name='comparison_results')
    op.drop_column('comparison_results', 'owner_id')
    op.drop_index(op.f('ix_comparison_documents_owner_id'), table_name='comparison_documents')
    op.drop_column('comparison_documents', 'owner_id')
    # ### end Alembic commands ###
