"""add_parent_id_to_rule_group

Revision ID: cbce25388b3d
Revises: 00f445f9da35
Create Date: 2025-12-23 14:45:09.929234

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'cbce25388b3d'
down_revision: Union[str, Sequence[str], None] = '00f445f9da35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('review_tasks', sa.Column('rule_group_names', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.alter_column('review_tasks', 'rule_group_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('rule_groups', sa.Column('parent_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_index(op.f('ix_rule_groups_parent_id'), 'rule_groups', ['parent_id'], unique=False)
    op.create_foreign_key(None, 'rule_groups', 'rule_groups', ['parent_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'rule_groups', type_='foreignkey')
    op.drop_index(op.f('ix_rule_groups_parent_id'), table_name='rule_groups')
    op.drop_column('rule_groups', 'parent_id')
    op.alter_column('review_tasks', 'rule_group_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('review_tasks', 'rule_group_names')
    # ### end Alembic commands ###
